### PR TITLE
tex: Unset proxy while knife run (bsc#958716)

### PR DESCRIPTION
**Pull request by rsalevsky**
Backport of #2208

### CODE REVIEW

**Comment by mjura** [comment]
Looks OK, +1

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
Actually: can you use `cherry-pick -x` for the commit?

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
@vuntz Feel free to merge.

**Pull request merged**
