### PR TITLE
install-chef-suse: xinetd is not used anymore

### PR DESCRIPTION
**Pull request by vuntz**
Required for https://github.com/crowbar/crowbar-core/pull/97

### CODE REVIEW

**Comment by jsuchome** [comment]
+1 once the other one is merged

**Comment by vuntz** [comment]
https://ci.suse.de/job/openstack-mkcloud/10560 is a gating build with all the patches required.

**Comment by MaximilianMeister** [comment]
@vuntz still wip? gating is already at tempest

**Comment by vuntz** [comment]
@MaximilianMeister oops, sorry, removed the tag.

**Comment by MaximilianMeister** [comment]
:+1: [gating](https://ci.suse.de/job/openstack-mkcloud/10560) is green meanwhile

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
