### PR TITLE
install-chef-suse: Remove setting REPOS_SKIP_CHECKS env var for DEPS iso

### PR DESCRIPTION
**Pull request by vuntz**
We don't check these repos in this script anymore.

### CODE REVIEW

**Comment by aplanas** [comment]
There are some references here:

https://github.com/vuntz/crowbar/blob/no-repos-skip/scripts/install-chef-suse.sh#L416

**Comment by vuntz** [comment]
> There are some references here:
> 
> https://github.com/vuntz/crowbar/blob/no-repos-skip/scripts/install-chef-suse.sh#L416

But they're only for PTF repos, not for Pool/Updates. Maybe the commit message needs to be clearer?

**Comment by aplanas** [comment]
Ah OK, is only dropping the extension of this in the media

**Comment by aplanas** [comment]
+1

**Comment by mjura** [comment]
+1

**Pull request merged**
