### PR TITLE
Rename some directories and files

### PR DESCRIPTION
**Pull request by vuntz**
This is to avoid any potential confusion with the names.

### CODE REVIEW

**Comment by tboerger** [comment]
What about just ```scripts``` instead of ```install-scripts```? :)

**Comment by aplanas** [comment]
LGTM +1

**Comment by tboerger** [comment]
Maybe you can remove ```gem 'pry-byebug', '>= 3.1.0'``` from the gemfile as well? And restructure the readmes into the docs folder? :)

**Comment by vuntz** [comment]
@tboerger all done

**Comment by tboerger** [comment]
Does the part 

```
COMPONENT LICENSES:

Please see https://github.com/crowbar/crowbar/wiki/Licenses-for-Components
```

really make sense? I would suggest to put a plain Apache-2.0 license into the LICENSE file. It's obvious that some components may got different licenses than the codebase of crowbar itself.

**Comment by tboerger** [comment]
Just the LICENSE thing, beside that I like that!

**Comment by vuntz** [comment]
@tboerger done

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Pull request merged**
