### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### crowbar/crowbar now has a Chat Room on Gitter

@tboerger has just created a chat room. You can visit it here: [https://gitter.im/crowbar/crowbar](https://gitter.im/crowbar/crowbar?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/crowbar/crowbar?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by aspiers** [comment]
-1, we should use IRC not Gitter.

**Comment by tboerger** [comment]
I definitly prefer gitter.

**Comment by aspiers** [comment]
If you want us to switch from IRC to Gitter, please provide *concrete reasons* justifying the switch.  I already provided some concrete reasons against it.  If your reasons outweigh those then I am happy to vote for switching.  But the reasons need to be more persuasive than "it's cool and shiny".

**Comment by aspiers** [comment]
And BTW this discussion should happen using the community's *existing* communication channels, i.e. IRC and/or the mailing list.  It makes no sense to argue for switching to Gitter on the Gitter channel itself before any switch is decided.

**Comment by tboerger** [comment]
@aspiers I have announced that on IRC as well, currently you are the only one that complains about it. As there is currently simply no community it makes sense to open multiple channels to get in contact with developers. And btw there is an IRC gateway, so you can use it with your IRC client as well.

**Comment by rsalevsky** [comment]
We should try everything which brings us near to the community and this includes new communication ways. So when there is a gateway it has no negative effects. I like gitter, it's much more comfortable as IRC and it's easier to join the channel and ask questions.

But we should use https://gitter.im/crowbar instead of https://gitter.im/crowbar/crowbar.

**Comment by tboerger** [comment]
I have no strong opinion on crowbar/crowbar or just crowbar. I just have not seen the org only chat before :)

**Comment by aspiers** [comment]
> @aspiers I have announced that on IRC as well, currently you are the only one that complains about it.

Probably I am the only one who noticed ;-p  The mailing list would be the right place to discuss this ...  unfortunately it seems we have no mailing list any longer :-(  (I don't count the opencrowbar google group.)  Actually I added that issue to [our backlog](https://trello.com/c/DVcpR1UJ) earlier today - we really must have a mailing list.

> As there is currently simply no community

That is not accurate.  Your personal opinion represents something like 5% of active developers, and much less than that if you count users.  So please ask the other 95+% for their opinions before making decisions which affect us all.

> it makes sense to open multiple channels to get in contact with developers.

It seems you are assuming that creating more places to talk is likely to encourage more discussion?  But I don't know why you think that.  People don't randomly guess the location of chat forums - typically they search for them on the project's website.  And there are multiple downsides of having two separate channels:

1. It creates a big risk of people missing discussions by only being in one channel
2. It requires people to monitor two channels
3. It's confusing to newbies
4. It creates unnecessary maintenance overhead

> And btw there is an IRC gateway, so you can use it with your IRC client as well.

Well OK, that's nice.  In that case, I am personally willing to *consider* moving to Gitter, even though I don't like that it is a move from a free (libre) technology to a proprietary one (BTW don't you care about that at all?).

But please let's have a proper discussion with *everyone* about it, instead of one or two people just making the decision without first asking the rest of the community.

**Comment by aspiers** [comment]
@rsalevsky  wrote:
> We should try everything which brings us near to the community and this includes new communication ways.

I'm always open to trying things.  But sorry, IMHO claiming that moving to gitter "brings us near to the community" is totally false.  If you really believe that, please explain why.  I am willing to be convinced if you have good reasons ;-)

> So when there is a gateway it has no negative effects.

Not true, because people are already using #crowbar on Freenode.  Unless you have a proper discussion with those people about the idea of switching, there are definitely negative effects.

> I like gitter, it's much more comfortable as IRC and it's easier to join the channel and ask questions.

That's your personal opinion, but it's not shared by everyone.  For example, *why* do you think it's easier to join?  Can you explain that in detail?  Why is it more comfortable?  I suspect if you think carefully about why you like it, you will find the main reason is that it looks nicer.  I agree that it looks nice and shiny, but that is not the only thing you should think about, or even the most important one :-)

**Comment by rsalevsky** [comment]
@aspiers:

> I'm always open to trying things. But sorry, IMHO claiming that moving to gitter "brings us near to the community" is totally false. If you really believe that, please explain why. I am willing to be convinced if you have good reasons ;-)

Sure, new communication ways opens always new possibility's to get in touch with the other community members. That's basically the same system why the most company's / community's uses Facebook / Twitter. The first touch with someone is the biggest barrier between people. Conversely, that means they uses always the most comfortable way and IRC is not that comfortable. We can not expect that everyone uses IRC so the barrier is higher.

> Not true, because people are already using #crowbar on Freenode. Unless you have a proper discussion with those people about the idea of switching, there are definitely negative effects.

Maybe I misunderstood something, I thought gateway means a connection between the IRC channel and the gitter channel. So everyone can choose what they prefer and all are happy. When gateway means just a way to connect with a IRC client to gitter then let's implement a "real" gateway as bridge. Should be very easy and finished with few lines of code.

> That's your personal opinion, but it's not shared by everyone. For example, why do you think it's easier to join? Can you explain that in detail? Why is it more comfortable? I suspect if you think carefully about why you like it, you will find the main reason is that it looks nicer. I agree that it looks nice and shiny, but that is not the only thing you should think about, or even the most important one :-)

What's easier and faster? Click two buttons or search for a IRC client install them, search for all the config stuff and so on. It's the same reason as I sayed above. You can not expect that everyone has experience with IRC and uses IRC. My experience is that the most people will join ask few questions and leave and only a small amount stays for a longer time. But this is the way how a community grows.

**Comment by aspiers** [comment]
I moved this discussion to cloud@suse.de, so that the whole community can see it.  Please do not continue discussing here - thanks.

**Comment by vuntz** [comment]
I don't have any strong feeling, but I think we should list the mailing list and IRC too (not just gitter) if we do this change.

**Comment by tboerger** [comment]
I will create a pull request for that. Let's close this wrong one for now.

**Pull request closed without merging**
