### PR TITLE
install-chef-suse: Remove creation of symlinks to SMT mirror

### PR DESCRIPTION
**Pull request by vuntz**
This is moved to crowbar itself now.

Depends on https://github.com/crowbar/crowbar-core/pull/133

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
:+1:

**Comment by mjura** [comment]
+1

**Comment by tboerger** [comment]
Needs rebase

**Comment by vuntz** [comment]
rebased

**Comment by vuntz** [comment]
@mjura @rsalevsky @tboerger just checking: are your +1 from before the rebase still valid?

**Comment by mjura** [comment]
Yes, I'm happy +1

**Pull request merged**
