### PR TITLE
Add branding_install.rb script

### PR DESCRIPTION
**Pull request by vuntz**
This is a small utility to regenerate files that need to be updated once
Crowbar branding package has been installed.

This is needed for the branding subpackage; this could however live directly as a source file in our crowbar package. What do people think?

### CODE REVIEW

**Comment by tboerger** [comment]
First of all you should remove the `.rb` extensions. After that you should not rely on `barclamp_mgmt_lib` as this will be dropped with next version of crowbar ;)

**Comment by vuntz** [comment]
> First of all you should remove the .rb extensions.

I'm just being consistent with barclamp_install.rb. Yes, it's horrible, but I'm in favor of consistency. I'm fine renaming all the utilities; can be done before or after this PR (if before, I'll update this PR).

> After that you should not rely on barclamp_mgmt_lib as this will be dropped with next version of crowbar ;)

Hrm, but the only real important piece of code in the small utility is the call to `generate_assets_manifest`. Do you want to copy the method here instead?

**Comment by tboerger** [comment]
> Hrm, but the only real important piece of code in the small utility is the call to generate_assets_manifest. Do you want to copy the method here instead?

Sorry, forget it. I were talking about `barclamp_lib.rb`.

> I'm just being consistent with barclamp_install.rb. Yes, it's horrible, but I'm in favor of consistency. I'm fine renaming all the utilities; can be done before or after this PR (if before, I'll update this PR).

Than let's do it afterwards for both scripts.

**Comment by tboerger** [comment]
:+1:

**Comment by aplanas** [comment]
Even if is only called in OBS / IBS, for me makes sense to be here.

+1

**Comment by tboerger** [comment]
I think I will build some different commands for barclamp_* soon as well but for now it's fine like it is.

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
