### PR TITLE
Support SLES12 SP2, but not require it for Cloud repository

### PR DESCRIPTION
**Pull request by jsuchome**
Based on https://github.com/crowbar/crowbar/pull/2227

I know that last commit is ugly, but do we need more elegant solution?

### CODE REVIEW

**Comment by jsuchome** [comment]
Hm, but we would need to comment all checks for SP2 repos...

**Comment by vuntz** [comment]
> Hm, but we would need to comment all checks for SP2 repos...

I was going to point this out :-) Just disable the checks for now in general, I guess.

**Comment by rsalevsky** [comment]
My plan was to use SP2 as default for the admin node and just check the SP2 repo.

**Comment by jsuchome** [comment]
Yes, that might be done later. Current requirement is to enable SP2 nodes to be installed, but not having it a default. That's why @bmwiedemann added an option for that https://github.com/SUSE-Cloud/automation/pull/1008

**Comment by vuntz** [comment]
+1

**Comment by rsalevsky** [comment]
Same is done in https://github.com/crowbar/crowbar/pull/2227, except disabling repo checks for SP2.

**Comment by jsuchome** [comment]
@rsalevsky indeed, and it is mentioned above (I'm cherry-picking your commit). But those other 2 commits are needed as well.

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
