### PR TITLE
Merge asset manifests on install/uninstall

### PR DESCRIPTION
**Pull request by vuntz**
We obviously need to copy the manifests in a directory on install to
make sure we keep them. Note that on install, if we see the barclamp
doesn't have a manifest, we ensure that there's no old manifest
installed for that barclamp.

### CODE REVIEW

**Comment by tboerger** [comment]
Please use ```Pathname```, it makes multiple file handling much easier like ```join```, or ```read``` without calling seperate ```File```.

**Comment by tboerger** [comment]
```ruby
def manifests_path
  @manifests_path ||= Pathname.new(CROWBAR_PATH).join("barclamps", "manifests")
end
```

**Comment by vuntz** [comment]
@tboerger actually, I'd prefer to avoid this: this makes a totally different style than what exists in the same code path (in `bc_install_layout_1_ap`), which makes it hard to read. I'm happy to switch to `Pathname`, but really, we should switch everything to it in that case. And I'd prefer another PR for this.

**Comment by tboerger** [comment]
I already mentioned that on the other mgmt lib improvement (related to migrations) opened by you. IMHO the Pathname approach makes it much better readable because you can simply call nearby all ```File```, ```FileUtils``` and more methods on the ```Pathname``` object.

**Comment by vuntz** [comment]
@tboerger I don't disagree it's a good move; I disagree here because if you look a few lines earlier, we have the same code already not using `Pathname`. So we should do the move, but switching everything together, to avoid having two similar code paths look totally different.

**Comment by tboerger** [comment]
So maybe we need to solve that later on...

**Comment by vuntz** [comment]
At this point, this has been tested as a package patch for quite some time => merging.

**Pull request merged**
