### PR TITLE
Replaced guard files with a single file

### PR DESCRIPTION
**Pull request by tboerger**
Currently there are still some quirks required like switching the Gemfile url to http instead of https, but I think this is more related to the ruby packaging and versions on our SLE 11 nodes. In general it seems to work fine, feel free to try it!

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1 It's not perfect but it works unlike the old Guardfiles but we should optimize it.

**Comment by tboerger** [comment]
I think we can optimize many parts when we simplify the structure of this repository afterwards.

**Comment by rsalevsky** [comment]
Please add line below to the `.gitignore`
```
.guard-*
```

**Comment by tboerger** [comment]
@rsalevsky there is already an gitignore for these files.

**Comment by rsalevsky** [comment]
@tboerger sorry overlooked this

**Comment by vuntz** [comment]
No objection on my side (not giving a real +1 as I'm not using this and can't say whether it's an improvement or not; I'll let the people using guard files decide)

**Comment by rsalevsky** [comment]
I will merge this PR now, as far as I know there is only @tboerger and me who using this.

**Pull request merged**
