### PR TITLE
Replace md5 checksum on repository keys with fingerprint (bsc# 988907)

### PR DESCRIPTION
**Pull request by nicolasbock**
(cherry picked from commit ff7add4a8878744d071d035f5e06e9b8f4b9d2e4)

### CODE REVIEW

**Comment by rsalevsky** [comment]
LGTM. just the space between bsc# and the bug number should be removed.

**Comment by nicolasbock** [comment]
@rsalevsky Thanks for pointing that out. I'll fix my commit messages.

**Comment by nicolasbock** [comment]
@rsalevsky Do you know what's going on with the Travis checks?

**Comment by nicolasbock** [comment]
I should note that we mainly need this patch in stable/3.0 since we have disabled the key verification in master due to the SP1 -> SP2 transition.

**Comment by rsalevsky** [comment]
#2244 should fix the issue

**Comment by dirkmueller** [comment]
-1 cherrypick git hash is wrong, please update/rebase (to retrigger travis-ci)

**Comment by nicolasbock** [comment]
@dirkmueller Fixed.

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
