### PR TITLE
(WIP, not tested) Clean up repo checks

### PR DESCRIPTION
**Pull request by dirkmueller**
Checking for the optional product identifier is wrong. Seems
like there was a repoid added for this purpose, so lets use that.

### CODE REVIEW

**Comment by tboerger** [comment]
What about this? Is this still useful or can it get closed?

**Comment by aspiers** [comment]
Looks useful to me - worth finishing.

**Comment by aspiers** [comment]
Superceded by #2081?

**Comment by dirkmueller** [comment]
partially.. anyway, lets close this, I won't get to it anytime soon.

**Pull request closed without merging**
