### PR TITLE
Remove unused directories

### PR DESCRIPTION
**Pull request by tboerger**
To get started with some cleanup i have started to remove folders that are not used anymore.

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by aspiers** [comment]
I'm in favour of cleanup, but we should not shut the door on multi-distro support.  In fact I think that is by far the best way to build a real community.  So :-1: until the wider team discusses this.

One option would be to add a `multi-distro-support` tag before merging this so that the code is easily retrievable later if we add support back in.  However there is still the risk that some Ubuntu/CentOS fan who is curious about Crowbar visits this github project, looks at the code, sees that only SUSE distros are supported, and then leaves before they discover that there is already a lot of prior work done on supporting these distros.  So I'm not convinced by that approach.

**Comment by tboerger** [comment]
I have remove ALL distro folders, even the SUSE ones. IMHO our goal have to be to build everything with tools like OBS. And all the distro folders are still available in the old master tag. So i think this :-1: is not really valid.

**Comment by aspiers** [comment]
Sorry but `old-master` is not a good tag name - when people look back in a year or two they will have NO clue what it refers to.  Please pick a more descriptive name that at least refers to a particular release, e.g. `pre-tex` but better than that.

**Comment by tboerger** [comment]
screenshot

Uhm, there are already branches for stoney and tex?

**Comment by tboerger** [comment]
And btw, old-master is used for ALL other barclamps.

**Comment by aspiers** [comment]
> Uhm, there are already branches for stoney and tex?

Yes - I heard that you created them independently even though @vuntz had [recommended to postpone creation until this sprint](https://github.com/crowbar/crowbar/pull/2093#issuecomment-99615828).  But they are already out of date, and also [the corresponding `_service` files have not been changed accordingly](https://build.suse.de/package/view_file/Devel:Cloud:5/crowbar/_service?expand=1), so they are currently unused.

[This task is in the current Grapes sprint](https://trello.com/c/9zb0vIcb), so please don't do anything else on it.

> And btw, old-master is used for ALL other barclamps.

Nope, it's missing from barclamp-pacemaker at very least.  And sorry, but even if it was used for *all* barclamps, that wouldn't magically convert it from being a bad name into a good name :-)  When people look back in a year or two they will have NO clue what `old-master` means.  That's like the pre-RCS approach to version control where people kept copies of files by appending suffices like `.old`, `.old.2`, and `.REALLY.OLD`.

**Comment by tboerger** [comment]
Ok forgot it. I will defintily stop improving this stuff now.

**Comment by aspiers** [comment]
@tboerger Either you misunderstood me, or you give up far too easily.  I made some constructive criticism on the branching issue, and I also think that more discussion regarding multi-OS support is needed before we start changing anything radically (this PR is *far* more invasive than the branch creation which @vuntz suggested postponing); however I am strongly in favour of clean-up in general.  Fixing the branch naming should be done by Grapes this sprint, and after that I expect it would make sense to consider merging this PR and others which remove other unmaintained code.

**Comment by tboerger** [comment]
I wanted to do some improvement, you have been the first person that wanted to have changes. This improvment have not been accepted so i will simply stop that. I don't want to discuss over and over again the same stuff. Do what you want with the cleanup in Grapes, i will just stop it as i have more then enough other things to do. That was just something i did to get something different than HAWK to see.

**Comment by aspiers** [comment]
> This improvment have not been accepted so i will simply stop that.

Why?  Do you give up every time one of your PRs receives some constructive criticism?  If we all did that, the team would make no progress at all.

> I don't want to discuss over and over again the same stuff.

We are not discussing the same stuff over and over.  We only discussed it once, and then you closed the PR.  I'm not sure why.  I guess maybe you were offended by me saying `old-master` was a bad name for a branch?  If so then feel free to ask me to be politer and I will apologise and try to use gentler words in future, but I hope we can avoid letting emotions get in the way of valid technical discussions.

**Comment by tboerger** [comment]
I alreadt know this endless discussions. And i won't do it again for this. Feel free to improve in Grapes. I will not start any more improvement before i get any card in that direction.

And for the naming of the branch... They are already there for multiple months and nobody cared about the naming. The same for cleaning up branches btw. Oh, wait, i have been the one that cleaned the stuff of others in that part...

And of course this old-master branch doesn't exist for pacemaker, this barclamp has been developed far later, just as a sidenode and shame on me that i don't remember that while i stated all barclamps got this branch.

And there will be no Ubuntu/CentOS or whatever fan get interested in that if there are nowhere some working images or packages available. But that's a totally different thing nobody really cares about.

**Comment by aspiers** [comment]
> I alreadt know this endless discussions.

They're not endless but it requires patience to reach a consensus.  Giving up simply because you disagree with someone does not help reach consensus.

> They are already there for multiple months and nobody cared about the naming.

That's not true, I always care about naming.  I don't remember you notifying the community before you created `old-master` - if you did I'm pretty sure I would have noticed and replied saying it was not a good choice.  But if I missed it I apologise. 

> And of course this old-master branch doesn't exist for pacemaker, this barclamp has been developed far later, just as a sidenode and shame on me that i don't remember that while i stated all barclamps got this branch.

This demonstrates why `old-master` is a not an ideal branch/tag name - it provides zero context for what "old" refers to, so it's not clear whether `old-master` is supposed to line up to the same point in time across all repos, or whether it's supposed to be independent per repo.  And as I already said, this will result in confusion when people look back at this in the future.  Maybe names like `pre-stoney`, `pre-tex` etc. are not hugely descriptive either, but at least they give some rough context to the timeframes involved.  Of course we could get more accurate by including a timestamp, but it's still not clear what that means.  In particular, we have had per-release branching in the barclamps for a LONG time, but not in the main Crowbar repo.  So trying to draw parallels between each regarding `old-master` doesn't make any sense.

> And there will be no Ubuntu/CentOS or whatever fan get interested in that if there are nowhere some working images or packages available.

True, which is why we need to discuss our cross-distro strategy.

> But that's a totally different thing nobody really cares about.

I don't think we've had enough discussions or had enough conclusions yet for that to be true.

**Comment by tboerger** [comment]
> True, which is why we need to discuss our cross-distro strategy.

We already discussed about that. and the only conclusion to keep it maintainable is to use OBS for the different distros.

> I don't think we've had enough discussions or had enough conclusions yet for that to be true.

Of course... Everybody sais "yeah, we need a community", "yeah, let's do it open for other interested people" and what happened? I have created everything on OBS, and nobody cares about it. Just look at OBS. I have been the only one who has done something on it...

**Comment by aspiers** [comment]
> We already discussed about that.

Then I think I missed that discussion :-(

> and the only conclusion to keep it maintainable is to use OBS for the different distros.

Yes, that seems like a good approach to me.

> Everybody sais "yeah, we need a community"

Not everybody.

> "yeah, let's do it open for other interested people" and what happened? I have created everything on OBS

What you have done so far is *super* cool, however it's not enough yet.  I suspect we'll need Ubuntu or Fedora packages.

> and nobody cares about it. Just look at OBS. I have been the only one who has done something on it...

Of course noone will notice until there is a good website, good quickstart documentation, an announcement, and some other noise on social media.  Surely you did not expect they would?  That is why I have been pushing for these things to be fixed for the last 2 years or so.  But it's great that FINALLY PM/PO are prioritizing this work in the sprints.  If we do it right, I really think people could start paying more attention.

**Comment by tboerger** [comment]
> What you have done so far is super cool, however it's not enough yet. I suspect we'll need Ubuntu or Fedora packages.

Of course we need, that, but do you want to write them? There had been one guy on IRC that had interest in that, but of course he lost interest because nothing happened.

> Of course noone will notice until there is a good website, good quickstart documentation, an announcement, and some other noise on social media. Surely you did not expect they would? That is why I have been pushing for these things to be fixed for the last 2 years or so. But it's great that FINALLY PM/PO are prioritizing this work in the sprints. If we do it right, I really think people could start paying more attention.

Even within SUSE nobody cared about it... That really requires no further attraction/website/documentation or whatever. Sorry that i really took a vacation and have not been there to guide through every step... The last release worked quite well on OBS, until somebody just started to copy it into IBS just because of being too lazy or whatever.

**Comment by aspiers** [comment]
> >  I suspect we'll need Ubuntu or Fedora packages.
>
> Of course we need, that, but do you want to write them?

No, I want PM/PO to decide a strategy regarding building the community, and then prioritize tasks like this according to that strategy.

> Even within SUSE nobody cared about it...

That's incorrect.  People are working on improving the website right now.  If noone within SUSE cared then that would not be happening.

> That really requires no further attraction/website/documentation or whatever.

Sorry, I have no idea what your point is here.  But a good website and docs ARE absolutely necessary.  Surely you are not disputing that?

> Sorry that i really took a vacation and have not been there to guide through every step...

No need to apologise - none of this should be dependent on individuals.  Like I already said, this requires careful discussion, prioritization, and planning within Scrum.  You seem to be suggesting that we need individuals to personally "care" in order for any of this to succeed, but that's not true.  It's a professional team effort based on shared goals.  We're not a bunch of hobbyists only working on this in our spare time (although of course hobbyists are always very welcome in the project too).

**Pull request closed without merging**
