### PR TITLE
Make install-chef-suse.sh aware of the SLE12 HA repos

### PR DESCRIPTION
**Pull request by vuntz**
This is a pre-requirement for having HA on SLE12.

### CODE REVIEW

**Comment by aspiers** [comment]
+1 assuming tested :)

**Comment by tboerger** [comment]
+1

**Comment by vuntz** [comment]
> +1 assuming tested :)

You're assuming too much for that one ;-)

**Comment by rsalevsky** [comment]
@vuntz I can test it but it needs a rebase first.

**Comment by vuntz** [comment]
rebased

**Comment by rsalevsky** [comment]
:+1:

**Comment by aspiers** [comment]
Is this tested now?

**Comment by rsalevsky** [comment]
Yes, I have tested this stuff.

**Pull request merged**
