### PR TITLE
Fix SES2 Pool check

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
should be obsproduct://build.suse.de/SUSE:SLE-12:Update:Products:SES2/ses/2/POOL/x86_64 instead

**Comment by vuntz** [comment]
@bmwiedemann is correct

**Comment by aplanas** [comment]
```xml
  <repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
   <revision>1442585631</revision>
   <tags>
     <repo>obsproduct://build.suse.de/SUSE:SLE-12:Update:Products:SES2/ses/2/POOL/x86_64</repo>
   </tags>
```

**Comment by dirkmueller** [comment]
@bmwiedemann thanks. fixed.

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
