### PR TITLE
fix package names for Cloud5

### PR DESCRIPTION
**Pull request by bmwiedemann**
we have ruby2.1 there

this only broke when trying to install from git

### CODE REVIEW

**Comment by tboerger** [comment]
:+1: for this fix, but I'm pretty sure this is not the only path where it needs to be fixed.

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Is the list of packages up-to-date, actually?

Also, I'm not sure we want to merge stuff in release/tex/master yet as we're not using the branches yet.

**Comment by tboerger** [comment]
Currently it have to be done against master, and not only for the tex path.

**Comment by dirkmueller** [comment]
-1, should be fixed in master instead of release/tex/master

**Pull request closed without merging**
