### PR TITLE
Append always .title to navi i18n keys

### PR DESCRIPTION
**Pull request by tboerger**
With that change we avoid the conflict with our branding branch for the future.

### CODE REVIEW

**Comment by rhafer** [comment]
+1 (We just have to make sure to fix the branding patch once more when merging this)

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
The branding branch is totally fine (https://github.com/SUSE-Cloud/crowbar-core/blob/master-branding/crowbar_framework/config/locales/crowbar/en.yml#L82-L86). Who wants to update the patch? I would suggest @rsalevsky :)

Than we can merge this.

**Comment by tboerger** [comment]
Merging, packages will be rebuilt now by @rsalevsky

**Pull request merged**
