### PR TITLE
Add branch for tex

### PR DESCRIPTION
**Pull request by vuntz**
This is a straight copy of the development files (cp releases/development releases/tex)

### CODE REVIEW

**Comment by tboerger** [comment]
You have to replace all the master strings within barclamp files.

**Comment by tboerger** [comment]
And we should remove all this bluepill stuff and the config files that are not used anymore.

**Comment by vuntz** [comment]
> You have to replace all the master strings within barclamp files.

Good catch, done.

> And we should remove all this bluepill stuff and the config files that are not used anymore.

That would be for another PR, imho.

**Comment by aspiers** [comment]
:-1:

I think it is well overdue that we start using branches properly in this repo, rather than this idiotic scheme.  All the people who previously objected to adopting the use of branches have long since stopped caring about this repo (and I never heard any convincing reasons for those objections anyway).  We have plenty of time before the next release to clean this up, so let's do it properly and end the madness:

- create a *git* branch for `tex`
- create a `pre-git-branches` tag to cover the unlikely scenario that anyone still relies on the old mechanism
- in `master`, scrap the entire `releases/` hierarchy, preserving only `releases/development/master/extra`, which could be renamed to `extra/` or maybe even something less vague.

**Comment by vuntz** [comment]
@aspiers hrm. Agree with you on the goal, but not sure I agree on the timing:

* Right now, everything is branched for tex, and this is the last change that we need to complete this. And we'll need to merge stuff like https://github.com/crowbar/crowbar/pull/2094 pretty fast to unbreak work on master.

* Unfortunately, killing the current scheme used by this repo probably requires a bit more care as this will impact old branches that we still keep alive, and the cleanup you suggest for master requires also some deeper look (if you ask me, I'd remove all files except what's inside releases/development/master/extra but that'd likely be too aggressive)

To me it sounds like the whole reorganization of this specific repo requires more planning and is a story in itself.

What do others think? I'm happy to just try switching to proper branches now, but then I'll ask people to help fix things this will break :-)

**Comment by aspiers** [comment]
> * Right now, everything is branched for tex, and this is the last change that we need to complete this.

Exactly why do you need this change?  Why wouldn't just creating a `tex` branch be enough?

> And we'll need to merge stuff like https://github.com/crowbar/crowbar/pull/2094 pretty fast to unbreak work on master.

Sure, and why couldn't you merge that instantly after creating the `tex` branch?

> Unfortunately, killing the current scheme used by this repo probably requires a bit more care as this will impact old branches that we still keep alive

Why?  Unless I'm forgetting something, that's the same argument which I heard from Dell, and I still don't see why it would impact anything at all.  The whole point of creating new branches is that they *can't* impact old branches.  That's what git branches are for.  What am I missing?

> and the cleanup you suggest for master requires also some deeper look

Not really - we already know which files inside `releases/development/master/` we care about, and there aren't many.

> (if you ask me, I'd remove all files except what's inside releases/development/master/extra but that'd likely be too aggressive)

That's what I already suggested ;-)

> To me it sounds like the whole reorganization of this specific repo requires more planning and is a story in itself.

That sounds like a great way to ensure it will never happen ;-p  Seriously, we had this conversation so many times already it's ridiculous.  Each time any action gets postponed due to fear of the unknown, but I've never heard *any* concrete argument why anything we care about would break.

> What do others think? I'm happy to just try switching to proper branches now, but then I'll ask people to help fix things this will break :-)

Well the only reason I can think of for postponing any longer is if you care about breaking `./dev`.  But in that case I'd probably also make some other highly unprofessional comments ;-)

Another way of looking at it is: what's the worst that could possibly happen?  This is git, after all.  Reverting changes is not very hard.

**Comment by vuntz** [comment]
First, I'm not sure that creating a card and getting it in the next sprint qualifies as "it will never happen" ;-)

> Another way of looking at it is: what's the worst that could possibly happen? This is git, after all. Reverting changes is not very hard.

Sure. But we're doing the initial setup to get Cloud 6 building and at the same time making sure that Cloud 5 doesn't break. Adding another layer of changes on top of that just makes it more complicated. Waiting that the dust settles a bit would help -- one less issue to care about while the full setup is being completed.

(btw, another thing I have in mind is that we should merge the git repos in a couple of repos like what was done for CB 2.0, but I guess that one is definitely bigger and shouldn't block any change like the one you suggest here)

**Comment by aspiers** [comment]
> First, I'm not sure that creating a card and getting it in the next sprint qualifies as "it will never happen" ;-)

Hmm, I can't imagine it receiving much more attention than our blogging stories, and those seem to be constantly deferred ;-p  (BTW not a personal criticism of anyone - I am just as guilty as anyone else on that front ...)

> > Another way of looking at it is: what's the worst that could possibly happen? This is git, after all. Reverting changes is not very hard.
> 
> Sure. But we're doing the initial setup to get Cloud 6 building and at the same time making sure that Cloud 5 doesn't break. Adding another layer of changes on top of that just makes it more complicated. Waiting that the dust settles a bit would help -- one less issue to care about while the full setup is being completed.

Sorry, but this just sounds like FUD to me.  How is `git branch tex && git push crowbar` "another layer of changes on top of that just makes it more complicated"?  That's the bit I really don't understand.  It seems an awful lot less complicated to me than creating yet another identical clone of 78 files which we know we don't need.  If I heard a *single* valid argument from *anyone* as to why that would introduce risk, then I would happily change my position and agree that we should take a bit more care over it.  But for the last 2 years all I've ever heard on this topic is a load of hand-waving based on zero facts ...

OK, so I'll accept that the third step I proposed ("in master, scrap the entire `releases/` hierarchy, preserving only `releases/development/master/extra`, which could be renamed to `extra/` or maybe even something less vague") brings in a small amount of risk.  But that's not even necessary at this point - that's just a nice-to-have which I agree would be perfectly reasonable to defer to the next sprint.  The branch creation is the bit which would save us having to pointlessly clone 78 files, and I see no reason to delay that.  Again, if you know of one, I'm all ears.

> (btw, another thing I have in mind is that we should merge the git repos in a couple of repos like what was done for CB 2.0, but I guess that one is definitely bigger and shouldn't block any change like the one you suggest here)

You mean like merging all the core barclamps into one repo?  Yeah, that would definitely make sense, and I totally agree that's out of scope here.  But we should file a card for it for sure!

**Comment by vuntz** [comment]
First, I'm not saying this would take ages; yes, it's probably 5 minutes for just doing it. But preparing is a bit longer (still, not too long, I agree)

> Sorry, but this just sounds like FUD to me.  How is `git branch tex && git push crowbar` "another layer of changes on top of that just makes it more complicated"?  That's the bit I really don't understand.

So there are a few things to ado and a few things to discuss:
* you need to also update our packages accordingly (trivial)
* the tex branch would actually not be correct (you would also need to change the files to point to the release/tex/master branches if you want to keep consistency, otherwise we can just kill the crap in the tex branch directly)
* do we need to create a stoney (and roxy) branch? Or do we use the tex branch (this sounds weird)
* what do I do in master about everything that I don't know about? Just kill it? Even if it's in extra? What if stuff in extra that we do not use but that we want to keep depends on something outside of extra? In the end, I would probably look quickly at all files, just to see if stuff needs to be kept (hey, did you know we should keep sledgehammer-common? And what about the travis-ci directory?)

Again, this is mostly trivial stuff. But in the end, that's totally orthogonal to the problem of getting post-tex unblocked and working without breaking tex, which is why I didn't want to deal with it for now.

**Comment by aspiers** [comment]
> So there are a few things to do and a few things to discuss:
> 
> * you need to also update our packages accordingly (trivial)

AFAICS, only `crowbar/_service` in D:C:5 and D:C:5:S need to be updated to point to the new `tex` branch, but that's no more work than in your way where you need to update the `%release_branch` macro definition in `crowbar.spec` from `releases/development/master` to `releases/tex/master`.  So it's a tie on this point.

> * the tex branch would actually not be correct (you would also need to change the files to point to the release/tex/master branches if you want to keep consistency, otherwise we can just kill the crap in the tex branch directly)

That sounds wrong to me, so one of us must be missing something.  Are you talking about `releases/$RELEASE/master/barclamp-*`?  I already said that these are irrelevant since we no longer care about `./dev`.  Or do you mean some other files?  If so, which ones, and why do they need to be changed?

> * do we need to create a stoney (and roxy) branch? Or do we use the tex branch (this sounds weird)

Sure, we could create `stoney` and `roxy` branches too.  OK, so that would mean two more `git branch` commands to run, and four more `_service` files to change, adding about 2 minutes to the overall task time.

> * what do I do in master about everything that I don't know about?

Initially, just leave it there.  Like I said, the cleanup is "just a nice-to-have which I agree would be perfectly reasonable to defer to the next sprint".

> Just kill it? Even if it's in extra? What if stuff in extra that we do not use but that we want to keep depends on something outside of extra? In the end, I would probably look quickly at all files, just to see if stuff needs to be kept (hey, did you know we should keep sledgehammer-common? And what about the travis-ci directory?)

There's *loads* of crap we could kill, of course.  But noone cared enough to kill it up till now, so my proposal is independent of that.  Additionally, starting to use real git branches per release gives us a *much safer way to kill it* than if we carry on the braindead practice of using `master` for everything, because if we break something whilst doing cleanup, it's the difference between potentially only screwing up the current release in development, and screwing up *every single release ever*.  Again, this is exactly what branches were designed for, and not using them *before* embarking on anything potentially risky is just crazy IMHO.

> Again, this is mostly trivial stuff. But in the end, that's totally orthogonal to the problem of getting post-tex unblocked and working without breaking tex, which is why I didn't want to deal with it for now.

Well I think I just dealt with it, didn't I? :-)

**Comment by aspiers** [comment]
Having got that rant out of my system, and in the interests of pretending like I'm a reasonable kind of guy ... ;)  - if for some reason you're still convinced that it's better to clone 78 files in one sprint and then de-duplicate them again in the sprint after, I'll be puzzled but I won't try to stand in your way.  BUT if the de-duplication / cleanup *doesn't* happen in the immediate next sprint, I'll be REALLY unhappy!!

**Comment by zehicle** [comment]
+1 - I think you're proposal makes sense.  Thank for you the detailed 
proposal.

On 05/06/2015 06:11 PM, Adam Spiers wrote:
>
>     So there are a few things to do and a few things to discuss:
>
>       * you need to also update our packages accordingly (trivial)
>
> AFAICS, only |crowbar/_service| in D:C:5 and D:C:5:S need to be 
> updated to point to the new |tex| branch, but that's no more work than 
> in your way where you need to update the |%release_branch| macro 
> definition in |crowbar.spec| from |releases/development/master| to 
> |releases/tex/master|. So it's a tie on this point.
>
>       * the tex branch would actually not be correct (you would also
>         need to change the files to point to the release/tex/master
>         branches if you want to keep consistency, otherwise we can
>         just kill the crap in the tex branch directly)
>
> That sounds wrong to me, so one of us must be missing something. Are 
> you talking about |releases/$RELEASE/master/barclamp-*|? I already 
> said that these are irrelevant since we no longer care about |./dev|. 
> Or do you mean some other files? If so, which ones, and why do they 
> need to be changed?
>
>       * do we need to create a stoney (and roxy) branch? Or do we use
>         the tex branch (this sounds weird)
>
> Sure, we could create |stoney| and |roxy| branches too. OK, so that 
> would mean two more |git branch| commands to run, and four more 
> |_service| files to change, adding about 2 minutes to the overall task 
> time.
>
>       * what do I do in master about everything that I don't know about?
>
> Initially, just leave it there. Like I said, the cleanup is "just a 
> nice-to-have which I agree would be perfectly reasonable to defer to 
> the next sprint".
>
>     Just kill it? Even if it's in extra? What if stuff in extra that
>     we do not use but that we want to keep depends on something
>     outside of extra? In the end, I would probably look quickly at all
>     files, just to see if stuff needs to be kept (hey, did you know we
>     should keep sledgehammer-common? And what about the travis-ci
>     directory?)
>
> There's /loads/ of crap we could kill, of course. But noone cared 
> enough to kill it up till now, so my proposal is independent of that. 
> Additionally, starting to use real git branches per release gives us a 
> /much safer way to kill it/ than if we carry on the braindead practice 
> of using |master| for everything, because if we break something whilst 
> doing cleanup, it's the difference between potentially only screwing 
> up the current release in development, and screwing up /every single 
> release ever/. Again, this is exactly what branches were designed for, 
> and not using them /before/ embarking on anything potentially risky is 
> just crazy IMHO.
>
>     Again, this is mostly trivial stuff. But in the end, that's
>     totally orthogonal to the problem of getting post-tex unblocked
>     and working without breaking tex, which is why I didn't want to
>     deal with it for now.
>
> Well I think I just dealt with it, didn't I? :-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/crowbar/crowbar/pull/2093#issuecomment-99640060>.
>

-- 
   

Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO, Founder

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by aspiers** [comment]
Thanks Rob.  Your +1 got me curious enough about the history of this scheme, so I did a quick bit of archaeology which revealed that `./dev` not only has `flatten` (which got us in this mess in the first place ;-) but also `gitify-meta`, which would have gotten us out of it a long time ago, but sadly it was never used ...

* Nov 2012: [Victor's reply after I belatedly realised that branch flattening was (IMHO) a big mistake](http://lists.us.dell.com/pipermail/crowbar/2012-November/001845.html)
* Nov 2013: [my post to the list arguing for introducing release branches to this repo in order to avoid the need for a new organization whilst allowing risky work on CB2 to continue](http://lists.us.dell.com/pipermail/crowbar/2013-November/004086.html)
* Nov 2013: [crowbar/crowbar#1951 - Add support for git tracked metadata](https://github.com/crowbar/crowbar/pull/1951) via `./dev gitify-meta`
* Dec 2013: the [corresponding discussion on the list](http://lists.us.dell.com/pipermail/crowbar/2013-December/004174.html)

So this discussion seemed fairly pivotal in the eventual splitting off of OpenCrowbar.  I'm still sad that happened, as I don't think anyone benefitted from the technology and community being split in half.  Anyway, water under the bridge ...

Moving back to the present: we could maybe even still use `gitify-meta` to tidy up the releases hierarchy.  This might save some time over doing it manually, and also preserve it for posterity, in case anyone in the future wants to start using `./dev` again.

**Comment by bmwiedemann** [comment]
:+1: for merging as is and doing branches as a planned backlog item.
we can call the branch "legacy" which makes it clearer why roxy+stoney+tex are using the same one

**Comment by aspiers** [comment]
> :+1: for merging as is and doing branches as a planned backlog item.

Would be nice to hear your reasons for this.  I've given my reasons against in quite some detail.

> we can call the branch "legacy" which makes it clearer why roxy+stoney+tex are using the same one

I like that idea if we wanted to avoid a branch for each release, although I don't personally see the need to avoid, since as I already said it's about 2 minutes work to create them.

**Comment by tboerger** [comment]
I would like to reorganize this repo as well, but for the meantime it should be easier to just take it as it is. I think we have enough time to update all maintained versions to an ```old-master``` branch when we start to cleanup the current master.

**Comment by aspiers** [comment]
@tboerger I am not proposing reorganizing this repo as a first step, so I wonder if you understood my proposal.  What do you mean exactly by "take it as it is"?

**Comment by tboerger** [comment]
> What do you mean exactly by "take it as it is"?

That I'm fine with the pull request as it is.

**Comment by aspiers** [comment]
OK I give up and you all suck ;-)  I've created https://trello.com/c/9zb0vIcb to ensure this cleanup doesn't get postponed any longer.  @vuntz you said this would go in the next sprint, so I'm holding you to that :-)

**Comment by vuntz** [comment]
@aspiers thanks for the card! And don't hesitate to twist my arm in Vancouver ;-)

**Comment by tboerger** [comment]
@aspiers I already created a ```old-master``` tag as it exists for all barclamps. So cleaning the stuff can begin :)

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6cz9s8-go&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=9z2SyCnv&invitationId=6118771163356282881








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6cz9s8-go&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEmlI0lXkDM4QAAAVOo-H2wfExv5SKIK0P07mJZiXKReRklDa9MBJfbkJ5RpP43LRo0YMALDZ5R1cIMzZk9aE1TWiMwS6w09AOvNrtiM6BI_cIW89UxiysUY-huTL63a8uHQ93rSEZfUNL0Ib74o81XenWznI43YqUOkFO4N_JjnfR2U1WMnnooQNO0qT7Ys8of&eid=0-im6cz9s8-go


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6cz9s8-go&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
