### PR TITLE
install-chef-suse: Fix syntax error

### PR DESCRIPTION
**Pull request by nicolasbock**
Backport of 5069cbaf9ebcea93b493e8ecc1d5f9998fb9aa82

### CODE REVIEW

**Comment by rsalevsky** [comment]
Can you add (bsc#1004020) to the commit message?

**Comment by nicolasbock** [comment]
@rsalevsky done

**Comment by rsalevsky** [comment]
@nicolasbock `install-chef-suse: Fix syntax error (bsc#1004020)` would be better to follow the same style as usual

**Comment by aplanas** [comment]
@rsalevsky is a cherry-pick, not sure that is a good idea to change the format ...

**Comment by rsalevsky** [comment]
@aplanas That's fine as long we have the cherry-picked comment in the commit message. If we don't add the bsc number then the maint team complains.

**Comment by nicolasbock** [comment]
@rsalevsky Are you fine then with the current commit message? Or should I change it?

**Comment by rsalevsky** [comment]
@nicolasbock I would like if you can change it.

**Comment by aplanas** [comment]
@rsalevsky AFAICS it is: https://github.com/crowbar/crowbar/pull/2272/commits/0e224b8b11e35fd305e545d80001db7d7a84d5be

The PR message don't show it, but is in the commit at least

**Comment by Itxaka** [comment]
+1

**Comment by nicolasbock** [comment]
Failing in `cct`, not related to PR.

**Comment by nicolasbock** [comment]
@rsalevsky As far as I can tell, we are not testing the code path touched by this PR. Since it's a backport that has been in tree since April, I think it's safe to assume that we can merge this PR as well.

**Pull request merged**
