### PR TITLE
install-chef-suse: Fix syntax error

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
I guess unrelated, but travis complains: ```An error occurred while installing listen (3.1.1), and Bundler cannot continue.```

**Comment by MaximilianMeister** [comment]
> I guess unrelated, but travis complains: An error occurred while installing listen (3.1.1), and Bundler cannot continue.

just for reference, I have opened https://github.com/crowbar/crowbar/pull/2226 to address this

**Comment by tboerger** [comment]
:+1:

**Pull request merged**
