### PR TITLE
Add back commit removing rabbitmq credential creation

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

Please create a trello card for tracking and i can do the missing stuff next week when i'm back :)

**Comment by vuntz** [comment]
Dropped the second commit since we have https://github.com/crowbar/crowbar/pull/2078 now

**Comment by tboerger** [comment]
:+1:

**Comment by vuntz** [comment]
We ship that patch already, so merging.

**Pull request merged**
