### PR TITLE
Fix missing $REQUIRE_SLES11 for Storage-only deploys

### PR DESCRIPTION
**Pull request by tserong**
Signed-off-by: Tim Serong <tserong@suse.com>

### CODE REVIEW

**Comment by tserong** [comment]
I can't believe I missed this in the last commit :-/

**Comment by rsalevsky** [comment]
Is there a reason why the sles_11 repos are not needed for SES?

**Comment by tserong** [comment]
If you do an SES-only deploy, with SES 1.0+ you only deploy SLE 12 nodes, which themselves have no need for the SLE 11 repos, so I thought it made sense to remove the hard requirement.

(The admin node itself probably still wants them, for updates to it, though)

**Comment by rsalevsky** [comment]
Ok, thanks for the explanation. :+1:

**Comment by tboerger** [comment]
+1

**Pull request merged**
