### PR TITLE
Skip SES2 update checks

### PR DESCRIPTION
**Pull request by dirkmueller**
Update channel doesn't exist right now.

### CODE REVIEW

**Comment by aplanas** [comment]
+1 (Potentially fixing Jenkin's job 7925)

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
Actually, I think the issue is only for the Updates repo, isn't it?

**Comment by dirkmueller** [comment]
@vuntz right. removed pool and added a comment.

**Pull request merged**
