### PR TITLE
Don't create secrets.env file while install-chef-suse run

### PR DESCRIPTION
**Pull request by rsalevsky**
Creating the secrets.env file is now part of the package.

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by MaximilianMeister** [comment]
:+1:

**Comment by vuntz** [comment]
@rsalevsky can we not do this in the package, but in the systemd service file of crowbar with `ExecStartPre`? That would make it easier for people to develop from git...

**Comment by rsalevsky** [comment]
@vuntz I develop from git and there is no issue and you shouldn't use the service while developing anyway.

**Comment by tboerger** [comment]
> @rsalevsky can we not do this in the package, but in the systemd service file of crowbar with ExecStartPre? That would make it easier for people to develop from git...

While you are working from git you should run the rails app in development mode, there you don't need this env variable anyway as the secrets.yml from crowbar already provides it. We need this env variable only for production environment.

**Pull request merged**
