### PR TITLE
Install Manila barclamp if available

### PR DESCRIPTION
**Pull request by bmwiedemann**
inspired by commit 9a41d9e3829083688dcf3c19b3ca3952dbb88337

tested it to actually be used for the crowbar package

### CODE REVIEW

**Comment by toabctl** [comment]
Ah. Then https://github.com/crowbar/crowbar/commit/1527381400f9d84a7bdba1b4139f599eaadee21b was wrong. +1

**Comment by bmwiedemann** [comment]
also needed https://build.suse.de/package/rdiff/Devel:Cloud:5/patterns-cloud?linkrev=base&rev=3

**Comment by bmwiedemann** [comment]
note: related to PR #2132

**Comment by jdsn** [comment]
:+1: lgtm

**Pull request merged**
