### PR TITLE
install is already in $MEDIA

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by aspiers** [comment]
Could you make the commit message a bit less cryptic?

**Comment by vuntz** [comment]
+1 once commit message is fixed

**Comment by dirkmueller** [comment]
(I'd appreciate keeping this a bit open as I'd like to debug PR testing)

**Comment by MaximilianMeister** [comment]
@vuntz I guess this is superseded by https://github.com/crowbar/crowbar/pull/2125 ? then I will just close it

**Comment by vuntz** [comment]
@MaximilianMeister nope, I haven't taken your change in my PR. This will conflict, but we can rebase one or the other easily. Or I can take your change there if you prefer.

**Comment by MaximilianMeister** [comment]
@vuntz either way works for me, whatever is faster. do it as you prefer :-)

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
