### PR TITLE
Moving OpenStack Nova networks to barclamp-neutron (WIP)

### PR DESCRIPTION
**Pull request by mjura**
This is initial pull request for moving OpenStack Nova networks to barclamp-neutron.
This change will:
- simplify network configuration 
- gives better flexibility for user deployments.

Warning!!! Please don't merge this until it will be tested

### CODE REVIEW

**Comment by rsalevsky** [comment]
@mjura Can you give an status update?

**Comment by mjura** [comment]
Status is still open :) waiting when somebody will get proper Trello Card.

**Comment by rsalevsky** [comment]
@mjura, this repository got merged into [crowbar-core](https://github.com/crowbar/crowbar-core).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by tboerger** [comment]
Needs rebase and let's look if tests will succeed.

**Comment by mjura** [comment]
Don't have time to work on it. It can reopened in the future

**Pull request closed without merging**
