### PR TITLE
Reenable bashate travis testing for PRs

### PR DESCRIPTION
**Pull request by dirkmueller**
Apparently this code refactoring was never tested.

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
+1

**Comment by aspiers** [comment]
> Ignore E006: Line too long …
>
> There are dozens of offenders in the code meanwhile, and got
> no time to fix them all. Sorry Adam :)

So when will this be fixed, if not now?  There are 72 long lines in these 2 scripts.  I really doubt it would take more than 10-20 minutes to fix, which IMHO is a far better approach than adding an ignore which would probably stay there for another 3 years.  But if you really think it will take hours to insert 72 newline characters into two files then please add a story to the backlog for it and assign it to grapes.  Otherwise -1 from me, because this ignore will allow the technical debt to get worse before it gets better.

**Comment by dirkmueller** [comment]
@aspiers not all can be easily wrapped. I actually tried it and ended up running into areas where I need to test whether the constructs are behaving equivalent, and I just didn't have time for that. BTW, in case you missed it, E006 is also disabled in the bashate tests on other repos, so its not a one-off-thing.

**Comment by dirkmueller** [comment]
@aspiers in addition, the bashate line length check is totally broken :-(

see https://review.openstack.org/#/c/248253/

**Comment by aspiers** [comment]
> I actually tried it and ended up running into areas where I need to test whether the constructs are behaving equivalent, and I just didn't have time for that.

Ah OK.  So why not submit the fixes for the easy cases, if you already did them?  I'd be much more comfortable with this PR if there were only a few cases left to fix - even if they are a bit tricky, it makes it more likely that the remaining ones will be fixed soon.

It's unfortunate that Hound doesn't support shell, otherwise we could adopt an incremental approach to this.  However https://github.com/filib/codeclimate-shellcheck/ is another option which looks even more promising to me.

> BTW, in case you missed it, E006 is also disabled in the bashate tests on other repos, so its not a one-off-thing.

I don't see how that's relevant?  Bad code in one repo does not justify bad code in another :)

**Comment by dirkmueller** [comment]
@aspiers done

**Comment by aspiers** [comment]
There are still 34 E006 violations of which several look easily fixable to me.  However this is an improvement on before, so +0.2 from me.

**Comment by toabctl** [comment]
+1

**Comment by dirkmueller** [comment]
(created https://trello.com/c/IRHo5Bnx as a followup)

**Pull request merged**
